[workspace]

[package]
name = "some_cargo_osdk-osdk-bin"
version = "0.1.0"
edition = "2021"

[dependencies.some_cargo_osdk]
path = "/home/sc46/some_cargo_osdk"
default-features = false

[dependencies.osdk-frame-allocator]
version = "0.16.1"

[dependencies.osdk-heap-allocator]
version = "0.16.1"

[dependencies.ostd]
version = "0.16.1"

[features]
