action = "Run"

[aster_bin]
path = "some_cargo_osdk-osdk-bin.qemu_elf"
arch = "riscv64"
version = "0.1.0"
size = 14261464
stripped = false

[aster_bin.typ.Elf]
has_linux_header = false
has_pvh_header = false
has_multiboot_header = true
has_multiboot2_header = true

[aster_bin.modified_time]
secs_since_epoch = 1759803781
nanos_since_epoch = 734259099

[config]
work_dir = "/home/sc46/some_cargo_osdk"
target_arch = "riscv64"

[config.build]
profile = "dev"
features = []
no_default_features = false
override_configs = []
linux_x86_legacy_boot = false
strip_elf = false
encoding = "raw"
rustflags = " "

[config.run.boot]
kcmdline = ["--"]
method = "qemu-direct"

[config.run.grub]
grub_mkrescue = "grub-mkrescue"
boot_protocol = "multiboot2"
display_grub_menu = false

[config.run.qemu]
args = "-cpu rv64,zba=true,zbb=true -machine virt -m 1G --no-reboot -nographic -display none -serial chardev:mux -monitor chardev:mux -chardev stdio,id=mux,mux=on,signal=off,logfile=qemu.log"
path = "qemu-system-riscv64"
with_monitor = false

[config.run.build]
profile = "dev"
features = []
no_default_features = false
override_configs = []
linux_x86_legacy_boot = false
strip_elf = false
encoding = "raw"
rustflags = " "

[config.test.boot]
kcmdline = ["--"]
method = "qemu-direct"

[config.test.grub]
grub_mkrescue = "grub-mkrescue"
boot_protocol = "multiboot2"
display_grub_menu = false

[config.test.qemu]
args = "-cpu rv64,zba=true,zbb=true -machine virt -m 1G --no-reboot -nographic -display none -serial chardev:mux -monitor chardev:mux -chardev stdio,id=mux,mux=on,signal=off,logfile=qemu.log"
path = "qemu-system-riscv64"
with_monitor = false

[config.test.build]
profile = "dev"
features = []
no_default_features = false
override_configs = []
linux_x86_legacy_boot = false
strip_elf = false
encoding = "raw"
rustflags = " "

[last_modified]
secs_since_epoch = 1759803781
nanos_since_epoch = 754671630
